// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAccount = `-- name: ArchiveAccount :exec
UPDATE accounts SET archived = true WHERE id = $1
`

func (q *Queries) ArchiveAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveAccount, id)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name) VALUES ($1) RETURNING id, name, archived, created_at
`

func (q *Queries) CreateAccount(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccountIfUnused = `-- name: DeleteAccountIfUnused :execrows
DELETE FROM accounts
WHERE accounts.id = $1
  AND NOT EXISTS (SELECT 1 FROM pos WHERE pos.account_id = accounts.id)
`

// Hard-delete an account if no Pos references it. Safe because
// transactions.account_id was dropped in 0005 (Pos now owns the
// account FK), so pos is the only inbound reference. Returns rows
// affected: 0 means the account is either missing or still has Pos —
// the caller disambiguates with a follow-up GetAccount.
func (q *Queries) DeleteAccountIfUnused(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountIfUnused, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, archived, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, archived, created_at FROM accounts WHERE NOT archived ORDER BY name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsIncludingArchived = `-- name: ListAccountsIncludingArchived :many
SELECT id, name, archived, created_at FROM accounts ORDER BY archived, name
`

func (q *Queries) ListAccountsIncludingArchived(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsIncludingArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccounts = `-- name: SearchAccounts :many
SELECT id, name, archived, created_at FROM accounts
WHERE NOT archived
  AND lower(name) LIKE '%' || lower($1) || '%'
ORDER BY name
LIMIT 10
`

// Case-insensitive substring search by name for the global search box.
// Active accounts only; capped so one entity can't flood the results.
func (q *Queries) SearchAccounts(ctx context.Context, lower string) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccounts, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountName = `-- name: UpdateAccountName :one
UPDATE accounts SET name = $2 WHERE id = $1
RETURNING id, name, archived, created_at
`

type UpdateAccountNameParams struct {
	ID   pgtype.UUID
	Name string
}

// Rename an account. Account.name is free text per spec §4.1; no
// uniqueness constraint, so a rename to a clashing name is allowed.
func (q *Queries) UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountName, arg.ID, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}
