// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAccount = `-- name: ArchiveAccount :exec
UPDATE accounts SET archived = true WHERE id = $1
`

func (q *Queries) ArchiveAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveAccount, id)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name) VALUES ($1) RETURNING id, name, archived, created_at
`

func (q *Queries) CreateAccount(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, archived, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, archived, created_at FROM accounts WHERE NOT archived ORDER BY name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsIncludingArchived = `-- name: ListAccountsIncludingArchived :many
SELECT id, name, archived, created_at FROM accounts ORDER BY archived, name
`

func (q *Queries) ListAccountsIncludingArchived(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsIncludingArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
