// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: counterparties.sql

package dbq

import (
	"context"
)

const getOrCreateCounterparty = `-- name: GetOrCreateCounterparty :one
INSERT INTO counterparties (name)
VALUES ($1)
ON CONFLICT (name_lower) DO UPDATE
  SET name = counterparties.name  -- preserve original casing per spec §4.4
RETURNING id, name, name_lower, created_at
`

// Insert or return existing by case-insensitive name match.
// name_lower is generated; the unique constraint on it dedupes.
func (q *Queries) GetOrCreateCounterparty(ctx context.Context, name string) (Counterparty, error) {
	row := q.db.QueryRow(ctx, getOrCreateCounterparty, name)
	var i Counterparty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameLower,
		&i.CreatedAt,
	)
	return i, err
}

const listCounterparties = `-- name: ListCounterparties :many
SELECT id, name, name_lower, created_at FROM counterparties ORDER BY name_lower
`

func (q *Queries) ListCounterparties(ctx context.Context) ([]Counterparty, error) {
	rows, err := q.db.Query(ctx, listCounterparties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Counterparty
	for rows.Next() {
		var i Counterparty
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameLower,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCounterparties = `-- name: SearchCounterparties :many
SELECT id, name, name_lower, created_at FROM counterparties
WHERE name_lower LIKE lower($1) || '%'
ORDER BY name_lower
LIMIT 20
`

func (q *Queries) SearchCounterparties(ctx context.Context, lower string) ([]Counterparty, error) {
	rows, err := q.db.Query(ctx, searchCounterparties, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Counterparty
	for rows.Next() {
		var i Counterparty
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameLower,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
