// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: income_template.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIncomeTemplateLine = `-- name: AddIncomeTemplateLine :one
INSERT INTO income_template_line (template_id, pos_id, amount, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, template_id, pos_id, amount, sort_order, created_at
`

type AddIncomeTemplateLineParams struct {
	TemplateID pgtype.UUID
	PosID      pgtype.UUID
	Amount     int64
	SortOrder  int32
}

func (q *Queries) AddIncomeTemplateLine(ctx context.Context, arg AddIncomeTemplateLineParams) (IncomeTemplateLine, error) {
	row := q.db.QueryRow(ctx, addIncomeTemplateLine,
		arg.TemplateID,
		arg.PosID,
		arg.Amount,
		arg.SortOrder,
	)
	var i IncomeTemplateLine
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.PosID,
		&i.Amount,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const archiveIncomeTemplate = `-- name: ArchiveIncomeTemplate :exec
UPDATE income_template SET archived = true WHERE id = $1
`

func (q *Queries) ArchiveIncomeTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveIncomeTemplate, id)
	return err
}

const createIncomeTemplate = `-- name: CreateIncomeTemplate :one
INSERT INTO income_template (name, leftover_pos_id)
VALUES ($1, $2)
RETURNING id, name, leftover_pos_id, archived, created_at
`

type CreateIncomeTemplateParams struct {
	Name          string
	LeftoverPosID pgtype.UUID
}

func (q *Queries) CreateIncomeTemplate(ctx context.Context, arg CreateIncomeTemplateParams) (IncomeTemplate, error) {
	row := q.db.QueryRow(ctx, createIncomeTemplate, arg.Name, arg.LeftoverPosID)
	var i IncomeTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LeftoverPosID,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIncomeTemplateLine = `-- name: DeleteIncomeTemplateLine :exec
DELETE FROM income_template_line WHERE id = $1
`

func (q *Queries) DeleteIncomeTemplateLine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncomeTemplateLine, id)
	return err
}

const getIncomeTemplate = `-- name: GetIncomeTemplate :one
SELECT id, name, leftover_pos_id, archived, created_at FROM income_template WHERE id = $1
`

func (q *Queries) GetIncomeTemplate(ctx context.Context, id pgtype.UUID) (IncomeTemplate, error) {
	row := q.db.QueryRow(ctx, getIncomeTemplate, id)
	var i IncomeTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LeftoverPosID,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listIncomeTemplateLines = `-- name: ListIncomeTemplateLines :many
SELECT id, template_id, pos_id, amount, sort_order, created_at FROM income_template_line
WHERE template_id = $1
ORDER BY sort_order, created_at
`

// Returns lines in display order (sort_order, then created_at as
// tiebreaker). Caller folds these into the apply allocation.
func (q *Queries) ListIncomeTemplateLines(ctx context.Context, templateID pgtype.UUID) ([]IncomeTemplateLine, error) {
	rows, err := q.db.Query(ctx, listIncomeTemplateLines, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeTemplateLine
	for rows.Next() {
		var i IncomeTemplateLine
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.PosID,
			&i.Amount,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeTemplates = `-- name: ListIncomeTemplates :many
SELECT id, name, leftover_pos_id, archived, created_at FROM income_template
WHERE NOT archived
ORDER BY name
`

func (q *Queries) ListIncomeTemplates(ctx context.Context) ([]IncomeTemplate, error) {
	rows, err := q.db.Query(ctx, listIncomeTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeTemplate
	for rows.Next() {
		var i IncomeTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LeftoverPosID,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumIncomeTemplateLines = `-- name: SumIncomeTemplateLines :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM income_template_line
WHERE template_id = $1
`

// Total of all lines on the template — used to validate that the
// incoming amount meets or exceeds the template's required allocation.
func (q *Queries) SumIncomeTemplateLines(ctx context.Context, templateID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumIncomeTemplateLines, templateID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
