// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loan.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveLoanSubmission = `-- name: ApproveLoanSubmission :execrows
UPDATE loan_payment_submission
SET status = 'approved', decided_at = now(), decided_by = $2, transaction_id = $3
WHERE id = $1 AND status = 'pending'
`

type ApproveLoanSubmissionParams struct {
	ID            pgtype.UUID
	DecidedBy     pgtype.UUID
	TransactionID pgtype.UUID
}

// Flip pending → approved and link the appended money_in. Guarded on
// status = 'pending' so a double-approve is a no-op (0 rows affected). The
// caller wraps this with the transaction insert in a single DB tx.
func (q *Queries) ApproveLoanSubmission(ctx context.Context, arg ApproveLoanSubmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveLoanSubmission, arg.ID, arg.DecidedBy, arg.TransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelLoanSubmission = `-- name: CancelLoanSubmission :execrows
UPDATE loan_payment_submission
SET status = 'cancelled', decided_at = now()
WHERE id = $1 AND pos_id = $2 AND status = 'pending'
`

type CancelLoanSubmissionParams struct {
	ID    pgtype.UUID
	PosID pgtype.UUID
}

// Borrower-initiated cancel: only their own Pos's pending rows. pos_id is
// passed (not just id) so a borrower can't cancel another loan's submission.
func (q *Queries) CancelLoanSubmission(ctx context.Context, arg CancelLoanSubmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelLoanSubmission, arg.ID, arg.PosID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingLoanSubmissionsByPos = `-- name: CountPendingLoanSubmissionsByPos :one
SELECT count(*) FROM loan_payment_submission
WHERE pos_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingLoanSubmissionsByPos(ctx context.Context, posID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingLoanSubmissionsByPos, posID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoanAccess = `-- name: CreateLoanAccess :one
INSERT INTO loan_access (pos_id, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, pos_id, username, password_hash, created_at
`

type CreateLoanAccessParams struct {
	PosID        pgtype.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) CreateLoanAccess(ctx context.Context, arg CreateLoanAccessParams) (LoanAccess, error) {
	row := q.db.QueryRow(ctx, createLoanAccess, arg.PosID, arg.Username, arg.PasswordHash)
	var i LoanAccess
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createLoanSession = `-- name: CreateLoanSession :one
INSERT INTO loan_session (token, pos_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, pos_id, issued_at, expires_at
`

type CreateLoanSessionParams struct {
	Token     string
	PosID     pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateLoanSession(ctx context.Context, arg CreateLoanSessionParams) (LoanSession, error) {
	row := q.db.QueryRow(ctx, createLoanSession, arg.Token, arg.PosID, arg.ExpiresAt)
	var i LoanSession
	err := row.Scan(
		&i.Token,
		&i.PosID,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createLoanSubmission = `-- name: CreateLoanSubmission :one
INSERT INTO loan_payment_submission (pos_id, payer_name, amount, effective_date, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, pos_id, payer_name, amount, effective_date, note, status, submitted_at, decided_at, decided_by, reject_reason, transaction_id
`

type CreateLoanSubmissionParams struct {
	PosID         pgtype.UUID
	PayerName     string
	Amount        int64
	EffectiveDate pgtype.Date
	Note          *string
}

func (q *Queries) CreateLoanSubmission(ctx context.Context, arg CreateLoanSubmissionParams) (LoanPaymentSubmission, error) {
	row := q.db.QueryRow(ctx, createLoanSubmission,
		arg.PosID,
		arg.PayerName,
		arg.Amount,
		arg.EffectiveDate,
		arg.Note,
	)
	var i LoanPaymentSubmission
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.PayerName,
		&i.Amount,
		&i.EffectiveDate,
		&i.Note,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.RejectReason,
		&i.TransactionID,
	)
	return i, err
}

const deleteLoanSession = `-- name: DeleteLoanSession :exec
DELETE FROM loan_session WHERE token = $1
`

func (q *Queries) DeleteLoanSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteLoanSession, token)
	return err
}

const getLoanAccessByPos = `-- name: GetLoanAccessByPos :one
SELECT id, pos_id, username, password_hash, created_at FROM loan_access WHERE pos_id = $1
`

func (q *Queries) GetLoanAccessByPos(ctx context.Context, posID pgtype.UUID) (LoanAccess, error) {
	row := q.db.QueryRow(ctx, getLoanAccessByPos, posID)
	var i LoanAccess
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getLoanAccessByUsername = `-- name: GetLoanAccessByUsername :one
SELECT id, pos_id, username, password_hash, created_at FROM loan_access WHERE username = $1
`

func (q *Queries) GetLoanAccessByUsername(ctx context.Context, username string) (LoanAccess, error) {
	row := q.db.QueryRow(ctx, getLoanAccessByUsername, username)
	var i LoanAccess
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getLoanSession = `-- name: GetLoanSession :one
SELECT token, pos_id, issued_at, expires_at
FROM loan_session
WHERE token = $1 AND expires_at > now()
`

// Live (unexpired) borrower session. Caller checks pos_id == route :id.
func (q *Queries) GetLoanSession(ctx context.Context, token string) (LoanSession, error) {
	row := q.db.QueryRow(ctx, getLoanSession, token)
	var i LoanSession
	err := row.Scan(
		&i.Token,
		&i.PosID,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLoanSubmission = `-- name: GetLoanSubmission :one
SELECT id, pos_id, payer_name, amount, effective_date, note, status, submitted_at, decided_at, decided_by, reject_reason, transaction_id FROM loan_payment_submission WHERE id = $1
`

func (q *Queries) GetLoanSubmission(ctx context.Context, id pgtype.UUID) (LoanPaymentSubmission, error) {
	row := q.db.QueryRow(ctx, getLoanSubmission, id)
	var i LoanPaymentSubmission
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.PayerName,
		&i.Amount,
		&i.EffectiveDate,
		&i.Note,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.RejectReason,
		&i.TransactionID,
	)
	return i, err
}

const listLoanPos = `-- name: ListLoanPos :many
SELECT id, name, currency, target, archived, created_at, account_id, is_loan FROM pos WHERE is_loan AND NOT archived ORDER BY name
`

func (q *Queries) ListLoanPos(ctx context.Context) ([]Po, error) {
	rows, err := q.db.Query(ctx, listLoanPos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Po
	for rows.Next() {
		var i Po
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Target,
			&i.Archived,
			&i.CreatedAt,
			&i.AccountID,
			&i.IsLoan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoanSubmissionsByPos = `-- name: ListLoanSubmissionsByPos :many
SELECT id, pos_id, payer_name, amount, effective_date, note, status, submitted_at, decided_at, decided_by, reject_reason, transaction_id FROM loan_payment_submission
WHERE pos_id = $1
ORDER BY submitted_at DESC
LIMIT 100
`

func (q *Queries) ListLoanSubmissionsByPos(ctx context.Context, posID pgtype.UUID) ([]LoanPaymentSubmission, error) {
	rows, err := q.db.Query(ctx, listLoanSubmissionsByPos, posID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanPaymentSubmission
	for rows.Next() {
		var i LoanPaymentSubmission
		if err := rows.Scan(
			&i.ID,
			&i.PosID,
			&i.PayerName,
			&i.Amount,
			&i.EffectiveDate,
			&i.Note,
			&i.Status,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.RejectReason,
			&i.TransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLoanSubmissionsByPos = `-- name: ListPendingLoanSubmissionsByPos :many
SELECT id, pos_id, payer_name, amount, effective_date, note, status, submitted_at, decided_at, decided_by, reject_reason, transaction_id FROM loan_payment_submission
WHERE pos_id = $1 AND status = 'pending'
ORDER BY submitted_at DESC
`

func (q *Queries) ListPendingLoanSubmissionsByPos(ctx context.Context, posID pgtype.UUID) ([]LoanPaymentSubmission, error) {
	rows, err := q.db.Query(ctx, listPendingLoanSubmissionsByPos, posID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanPaymentSubmission
	for rows.Next() {
		var i LoanPaymentSubmission
		if err := rows.Scan(
			&i.ID,
			&i.PosID,
			&i.PayerName,
			&i.Amount,
			&i.EffectiveDate,
			&i.Note,
			&i.Status,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.RejectReason,
			&i.TransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredLoanSessions = `-- name: PurgeExpiredLoanSessions :execrows
DELETE FROM loan_session WHERE expires_at <= now()
`

func (q *Queries) PurgeExpiredLoanSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredLoanSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectLoanSubmission = `-- name: RejectLoanSubmission :execrows
UPDATE loan_payment_submission
SET status = 'rejected', decided_at = now(), decided_by = $2, reject_reason = $3
WHERE id = $1 AND status = 'pending'
`

type RejectLoanSubmissionParams struct {
	ID           pgtype.UUID
	DecidedBy    pgtype.UUID
	RejectReason *string
}

func (q *Queries) RejectLoanSubmission(ctx context.Context, arg RejectLoanSubmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectLoanSubmission, arg.ID, arg.DecidedBy, arg.RejectReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPosIsLoan = `-- name: SetPosIsLoan :exec
UPDATE pos SET is_loan = $2 WHERE id = $1
`

type SetPosIsLoanParams struct {
	ID     pgtype.UUID
	IsLoan bool
}

func (q *Queries) SetPosIsLoan(ctx context.Context, arg SetPosIsLoanParams) error {
	_, err := q.db.Exec(ctx, setPosIsLoan, arg.ID, arg.IsLoan)
	return err
}

const updateLoanAccessPassword = `-- name: UpdateLoanAccessPassword :exec
UPDATE loan_access SET password_hash = $2 WHERE pos_id = $1
`

type UpdateLoanAccessPasswordParams struct {
	PosID        pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateLoanAccessPassword(ctx context.Context, arg UpdateLoanAccessPasswordParams) error {
	_, err := q.db.Exec(ctx, updateLoanAccessPassword, arg.PosID, arg.PasswordHash)
	return err
}
