// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID
	Name      string
	Archived  bool
	CreatedAt pgtype.Timestamptz
}

type Counterparty struct {
	ID        pgtype.UUID
	Name      string
	NameLower string
	CreatedAt pgtype.Timestamptz
}

type Po struct {
	ID        pgtype.UUID
	Name      string
	Currency  string
	Target    *int64
	Archived  bool
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	Token     string
	UserID    pgtype.UUID
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	DisplayName        string
	TelegramIdentifier string
	CreatedAt          pgtype.Timestamptz
}
