// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pos.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePos = `-- name: ArchivePos :exec
UPDATE pos SET archived = true WHERE id = $1
`

func (q *Queries) ArchivePos(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archivePos, id)
	return err
}

const createPos = `-- name: CreatePos :one
INSERT INTO pos (name, currency, account_id, target)
VALUES ($1, $2, $3, $4)
RETURNING id, name, currency, target, archived, created_at, account_id
`

type CreatePosParams struct {
	Name      string
	Currency  string
	AccountID pgtype.UUID
	Target    *int64
}

func (q *Queries) CreatePos(ctx context.Context, arg CreatePosParams) (Po, error) {
	row := q.db.QueryRow(ctx, createPos,
		arg.Name,
		arg.Currency,
		arg.AccountID,
		arg.Target,
	)
	var i Po
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Target,
		&i.Archived,
		&i.CreatedAt,
		&i.AccountID,
	)
	return i, err
}

const getPos = `-- name: GetPos :one
SELECT id, name, currency, target, archived, created_at, account_id FROM pos WHERE id = $1
`

func (q *Queries) GetPos(ctx context.Context, id pgtype.UUID) (Po, error) {
	row := q.db.QueryRow(ctx, getPos, id)
	var i Po
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Target,
		&i.Archived,
		&i.CreatedAt,
		&i.AccountID,
	)
	return i, err
}

const listPos = `-- name: ListPos :many
SELECT id, name, currency, target, archived, created_at, account_id FROM pos WHERE NOT archived ORDER BY currency, name, id
`

func (q *Queries) ListPos(ctx context.Context) ([]Po, error) {
	rows, err := q.db.Query(ctx, listPos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Po
	for rows.Next() {
		var i Po
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Target,
			&i.Archived,
			&i.CreatedAt,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosIncludingArchived = `-- name: ListPosIncludingArchived :many
SELECT id, name, currency, target, archived, created_at, account_id FROM pos ORDER BY currency, name, id
`

func (q *Queries) ListPosIncludingArchived(ctx context.Context) ([]Po, error) {
	rows, err := q.db.Query(ctx, listPosIncludingArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Po
	for rows.Next() {
		var i Po
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Target,
			&i.Archived,
			&i.CreatedAt,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosAccount = `-- name: UpdatePosAccount :one
UPDATE pos SET account_id = $2 WHERE id = $1
RETURNING id, name, currency, target, archived, created_at, account_id
`

type UpdatePosAccountParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

// Reassign a Pos to a different Account. Snapshot semantics per spec
// §5.6: every historical money_in / money_out for this Pos is re-
// attributed to the new Account on the next balance read; no ledger
// entry is written. Returns the updated Pos so the caller can echo it.
func (q *Queries) UpdatePosAccount(ctx context.Context, arg UpdatePosAccountParams) (Po, error) {
	row := q.db.QueryRow(ctx, updatePosAccount, arg.ID, arg.AccountID)
	var i Po
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Target,
		&i.Archived,
		&i.CreatedAt,
		&i.AccountID,
	)
	return i, err
}
