// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pos.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePos = `-- name: ArchivePos :exec
UPDATE pos SET archived = true WHERE id = $1
`

func (q *Queries) ArchivePos(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archivePos, id)
	return err
}

const createPos = `-- name: CreatePos :one
INSERT INTO pos (name, currency, target)
VALUES ($1, $2, $3)
RETURNING id, name, currency, target, archived, created_at
`

type CreatePosParams struct {
	Name     string
	Currency string
	Target   *int64
}

func (q *Queries) CreatePos(ctx context.Context, arg CreatePosParams) (Po, error) {
	row := q.db.QueryRow(ctx, createPos, arg.Name, arg.Currency, arg.Target)
	var i Po
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Target,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getPos = `-- name: GetPos :one
SELECT id, name, currency, target, archived, created_at FROM pos WHERE id = $1
`

func (q *Queries) GetPos(ctx context.Context, id pgtype.UUID) (Po, error) {
	row := q.db.QueryRow(ctx, getPos, id)
	var i Po
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.Target,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listPos = `-- name: ListPos :many
SELECT id, name, currency, target, archived, created_at FROM pos WHERE NOT archived ORDER BY currency, name, id
`

func (q *Queries) ListPos(ctx context.Context) ([]Po, error) {
	rows, err := q.db.Query(ctx, listPos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Po
	for rows.Next() {
		var i Po
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Target,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosIncludingArchived = `-- name: ListPosIncludingArchived :many
SELECT id, name, currency, target, archived, created_at FROM pos ORDER BY currency, name, id
`

func (q *Queries) ListPosIncludingArchived(ctx context.Context) ([]Po, error) {
	rows, err := q.db.Query(ctx, listPosIncludingArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Po
	for rows.Next() {
		var i Po
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Target,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
