// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddIncomeTemplateLine(ctx context.Context, arg AddIncomeTemplateLineParams) (IncomeTemplateLine, error)
	// Flip pending → approved and link the appended money_in. Guarded on
	// status = 'pending' so a double-approve is a no-op (0 rows affected). The
	// caller wraps this with the transaction insert in a single DB tx.
	ApproveLoanSubmission(ctx context.Context, arg ApproveLoanSubmissionParams) (int64, error)
	ArchiveAccount(ctx context.Context, id pgtype.UUID) error
	ArchiveIncomeTemplate(ctx context.Context, id pgtype.UUID) error
	ArchivePos(ctx context.Context, id pgtype.UUID) error
	// Borrower-initiated cancel: only their own Pos's pending rows. pos_id is
	// passed (not just id) so a borrower can't cancel another loan's submission.
	CancelLoanSubmission(ctx context.Context, arg CancelLoanSubmissionParams) (int64, error)
	CountPendingLoanSubmissionsByPos(ctx context.Context, posID pgtype.UUID) (int64, error)
	CreateAccount(ctx context.Context, name string) (Account, error)
	CreateIncomeTemplate(ctx context.Context, arg CreateIncomeTemplateParams) (IncomeTemplate, error)
	CreateLoanAccess(ctx context.Context, arg CreateLoanAccessParams) (LoanAccess, error)
	CreateLoanSession(ctx context.Context, arg CreateLoanSessionParams) (LoanSession, error)
	CreateLoanSubmission(ctx context.Context, arg CreateLoanSubmissionParams) (LoanPaymentSubmission, error)
	CreatePos(ctx context.Context, arg CreatePosParams) (Po, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Hard-delete an account if no Pos references it. Safe because
	// transactions.account_id was dropped in 0005 (Pos now owns the
	// account FK), so pos is the only inbound reference. Returns rows
	// affected: 0 means the account is either missing or still has Pos —
	// the caller disambiguates with a follow-up GetAccount.
	DeleteAccountIfUnused(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteIncomeTemplateLine(ctx context.Context, id pgtype.UUID) error
	DeleteIncomeTemplateLinesByTemplate(ctx context.Context, templateID pgtype.UUID) error
	DeleteLoanSession(ctx context.Context, token string) error
	DeleteSession(ctx context.Context, token string) error
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	GetIncomeTemplate(ctx context.Context, id pgtype.UUID) (IncomeTemplate, error)
	GetLoanAccessByPos(ctx context.Context, posID pgtype.UUID) (LoanAccess, error)
	GetLoanAccessByUsername(ctx context.Context, username string) (LoanAccess, error)
	// Live (unexpired) borrower session. Caller checks pos_id == route :id.
	GetLoanSession(ctx context.Context, token string) (LoanSession, error)
	GetLoanSubmission(ctx context.Context, id pgtype.UUID) (LoanPaymentSubmission, error)
	// Insert or return existing by case-insensitive name match.
	// name_lower is generated; the unique constraint on it dedupes.
	GetOrCreateCounterparty(ctx context.Context, name string) (Counterparty, error)
	GetPos(ctx context.Context, id pgtype.UUID) (Po, error)
	// Single-pos variant of SumPosCashBalances for the §6.3 detail view.
	GetPosCashBalance(ctx context.Context, posID pgtype.UUID) (int64, error)
	GetSession(ctx context.Context, token string) (GetSessionRow, error)
	GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetUserByTelegramIdentifier(ctx context.Context, telegramIdentifier string) (User, error)
	// Insert a money_in / money_out row. Idempotency: ON CONFLICT on
	// idempotency_key returns the existing row; the (xmax = 0) projection
	// distinguishes a fresh insert (was_inserted=true) from a conflict
	// (was_inserted=false), so the application can skip the notification
	// loop on idempotent re-submission per spec §10.8. Duplicate POSTs
	// silently return the original record per spec §7.2.
	//
	// Account is implicit via pos.account_id (§4.2/§5.6); the transaction
	// itself doesn't carry account_id.
	InsertMoneyTransaction(ctx context.Context, arg InsertMoneyTransactionParams) (InsertMoneyTransactionRow, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListAccountsIncludingArchived(ctx context.Context) ([]Account, error)
	ListCounterparties(ctx context.Context) ([]Counterparty, error)
	// Returns lines in display order (sort_order, then created_at as
	// tiebreaker). Caller folds these into the apply allocation.
	ListIncomeTemplateLines(ctx context.Context, templateID pgtype.UUID) ([]IncomeTemplateLine, error)
	ListIncomeTemplates(ctx context.Context) ([]IncomeTemplate, error)
	ListLoanPos(ctx context.Context) ([]Po, error)
	ListLoanSubmissionsByPos(ctx context.Context, posID pgtype.UUID) ([]LoanPaymentSubmission, error)
	ListNotificationsForUser(ctx context.Context, userID pgtype.UUID) ([]Notification, error)
	// Open obligations where this pos is creditor (money it's owed) or
	// debtor (money it owes). Counts toward Pos.receivables and
	// Pos.payables on the detail view per spec §4.2.
	ListObligationsForPos(ctx context.Context, creditorPosID pgtype.UUID) ([]PosObligation, error)
	ListPendingLoanSubmissionsByPos(ctx context.Context, posID pgtype.UUID) ([]LoanPaymentSubmission, error)
	ListPos(ctx context.Context) ([]Po, error)
	ListPosIncludingArchived(ctx context.Context) ([]Po, error)
	// Account-side feed via pos.account_id (§5.6 snapshot semantics).
	// A Pos reassigned to this account brings its history along; a Pos
	// moved away takes its history with it.
	ListTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Transaction, error)
	// Joined view for the §6.1 list: pos.name + currency,
	// counterparty.name, plus the Pos's *current* account (§5.6 snapshot).
	// LEFT JOINs because Phase 7+ inter_pos rows have NULL pos_id /
	// counterparty_id (line items live in inter_pos_lines — to be
	// rendered when that phase ships).
	ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]ListTransactionsByDateRangeRow, error)
	// Chronological transactions touching this pos. Phase-7+ inter_pos lines
	// live in inter_pos_lines and are not yet wired; this query covers the
	// money_in / money_out path that Phase 6 ships. Account name is the
	// Pos's *current* account (§5.6 snapshot view).
	ListTransactionsByPos(ctx context.Context, posID pgtype.UUID) ([]ListTransactionsByPosRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) (int64, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	PurgeExpiredLoanSessions(ctx context.Context) (int64, error)
	PurgeExpiredSessions(ctx context.Context) (int64, error)
	RejectLoanSubmission(ctx context.Context, arg RejectLoanSubmissionParams) (int64, error)
	// Case-insensitive substring search by name for the global search box.
	// Active accounts only; capped so one entity can't flood the results.
	SearchAccounts(ctx context.Context, lower string) ([]Account, error)
	SearchCounterparties(ctx context.Context, lower string) ([]Counterparty, error)
	// Substring (not prefix) match for the global search box. SearchCounterparties
	// stays prefix-only for the transaction-form typeahead; this one is broader.
	SearchCounterpartiesContains(ctx context.Context, lower string) ([]Counterparty, error)
	// Case-insensitive substring search by name for the global search box.
	SearchIncomeTemplates(ctx context.Context, lower string) ([]IncomeTemplate, error)
	// Case-insensitive substring search by name for the global search box.
	// Active Pos only; capped to keep the results panel balanced.
	SearchPos(ctx context.Context, lower string) ([]Po, error)
	// Global search box: match on the free-text note or the counterparty
	// name. Joined like ListTransactionsByDateRange so results can render
	// the pos/account/counterparty context. Account is the Pos's *current*
	// account (§5.6 snapshot). Capped for the results panel.
	SearchTransactions(ctx context.Context, lower string) ([]SearchTransactionsRow, error)
	SetPosIsLoan(ctx context.Context, arg SetPosIsLoanParams) error
	// Per-account balance: signed sum of money_in / money_out account_amount
	// contributions, attributed via the Pos's current account_id (§5.6
	// snapshot view). LEFT JOINs keep zero-balance accounts in the result
	// so the home view's list of accounts matches ListAccounts row-for-row.
	SumAccountBalances(ctx context.Context) ([]SumAccountBalancesRow, error)
	// §10.5 reconciliation surface. Per pos currency C, sums the signed
	// account_amount of every money_in/_out where pos.currency = C. The
	// IDR row is the canonical "Σ(Account flows) == Σ(IDR Pos.cash)"
	// invariant. Non-IDR rows expose the historical IDR cost of funding
	// a non-IDR pos (account-side outlay) and are NOT directly comparable
	// to the pos-side total.
	SumAccountBalancesByPosCurrency(ctx context.Context) ([]SumAccountBalancesByPosCurrencyRow, error)
	// Total of all lines on the template — used to validate that the
	// incoming amount meets or exceeds the template's required allocation.
	SumIncomeTemplateLines(ctx context.Context, templateID pgtype.UUID) (int64, error)
	// Spending heatmap (§6.4): one row per (pos, month) summing pos_amount
	// for money_out transactions in the date range. Caller pivots to a
	// months × top-N-pos table and computes the top-N ranking from totals.
	SumMoneyOutByPosMonth(ctx context.Context, arg SumMoneyOutByPosMonthParams) ([]SumMoneyOutByPosMonthRow, error)
	// Per-pos cash balance: signed sum of money_in / money_out pos_amount per
	// (pos_id, currency). inter_pos lines are not yet wired (Phase 7+) so they
	// contribute zero. Currency comes from pos.currency since money_in/_out
	// always denominate pos_amount in the pos's currency (§4.3 / §5.1).
	SumPosCashBalances(ctx context.Context) ([]SumPosCashBalancesRow, error)
	UnreadCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	// Rename an account. Account.name is free text per spec §4.1; no
	// uniqueness constraint, so a rename to a clashing name is allowed.
	UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) (Account, error)
	UpdateIncomeTemplate(ctx context.Context, arg UpdateIncomeTemplateParams) error
	UpdateLoanAccessPassword(ctx context.Context, arg UpdateLoanAccessPasswordParams) error
	// Reassign a Pos to a different Account. Snapshot semantics per spec
	// §5.6: every historical money_in / money_out for this Pos is re-
	// attributed to the new Account on the next balance read; no ledger
	// entry is written. Returns the updated Pos so the caller can echo it.
	UpdatePosAccount(ctx context.Context, arg UpdatePosAccountParams) (Po, error)
	// Rename a Pos and/or change its budget target. Currency is
	// intentionally NOT mutable here — changing it would re-bucket every
	// past transaction's pos_amount semantics, which is the kind of
	// balance-mutating UPDATE spec §10.3 forbids. Callers wanting a
	// different currency archive this Pos and create a new one.
	UpdatePosNameAndTarget(ctx context.Context, arg UpdatePosNameAndTargetParams) (Po, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
