// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveAccount(ctx context.Context, id pgtype.UUID) error
	ArchivePos(ctx context.Context, id pgtype.UUID) error
	CreateAccount(ctx context.Context, name string) (Account, error)
	CreatePos(ctx context.Context, arg CreatePosParams) (Po, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSession(ctx context.Context, token string) error
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	// Insert or return existing by case-insensitive name match.
	// name_lower is generated; the unique constraint on it dedupes.
	GetOrCreateCounterparty(ctx context.Context, name string) (Counterparty, error)
	GetPos(ctx context.Context, id pgtype.UUID) (Po, error)
	GetSession(ctx context.Context, token string) (GetSessionRow, error)
	GetUserByTelegramIdentifier(ctx context.Context, telegramIdentifier string) (User, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListAccountsIncludingArchived(ctx context.Context) ([]Account, error)
	ListCounterparties(ctx context.Context) ([]Counterparty, error)
	ListPos(ctx context.Context) ([]Po, error)
	ListUsers(ctx context.Context) ([]User, error)
	PurgeExpiredSessions(ctx context.Context) (int64, error)
	SearchCounterparties(ctx context.Context, lower string) ([]Counterparty, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
