// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveAccount(ctx context.Context, id pgtype.UUID) error
	ArchivePos(ctx context.Context, id pgtype.UUID) error
	CreateAccount(ctx context.Context, name string) (Account, error)
	CreatePos(ctx context.Context, arg CreatePosParams) (Po, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSession(ctx context.Context, token string) error
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	// Insert or return existing by case-insensitive name match.
	// name_lower is generated; the unique constraint on it dedupes.
	GetOrCreateCounterparty(ctx context.Context, name string) (Counterparty, error)
	GetPos(ctx context.Context, id pgtype.UUID) (Po, error)
	GetSession(ctx context.Context, token string) (GetSessionRow, error)
	GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetUserByTelegramIdentifier(ctx context.Context, telegramIdentifier string) (User, error)
	// Insert a money_in / money_out row. Idempotency: ON CONFLICT on
	// idempotency_key returns the existing row; the (xmax = 0) projection
	// distinguishes a fresh insert (was_inserted=true) from a conflict
	// (was_inserted=false), so the application can skip the notification
	// loop on idempotent re-submission per spec §10.8. Duplicate POSTs
	// silently return the original record per spec §7.2.
	InsertMoneyTransaction(ctx context.Context, arg InsertMoneyTransactionParams) (InsertMoneyTransactionRow, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListAccountsIncludingArchived(ctx context.Context) ([]Account, error)
	ListCounterparties(ctx context.Context) ([]Counterparty, error)
	ListNotificationsForUser(ctx context.Context, userID pgtype.UUID) ([]Notification, error)
	ListPos(ctx context.Context) ([]Po, error)
	ListTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Transaction, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) (int64, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	PurgeExpiredSessions(ctx context.Context) (int64, error)
	SearchCounterparties(ctx context.Context, lower string) ([]Counterparty, error)
	UnreadCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
