// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPosCashBalance = `-- name: GetPosCashBalance :one
SELECT COALESCE(SUM(CASE
    WHEN type = 'money_in'  THEN pos_amount
    WHEN type = 'money_out' THEN -pos_amount
    ELSE 0
END), 0)::bigint AS balance
FROM transactions
WHERE pos_id = $1
`

// Single-pos variant of SumPosCashBalances for the §6.3 detail view.
func (q *Queries) GetPosCashBalance(ctx context.Context, posID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPosCashBalance, posID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, type, effective_date, account_id, account_amount, pos_id, pos_amount, counterparty_id, note, source, created_by, idempotency_key, created_at, reverses_id FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EffectiveDate,
		&i.AccountID,
		&i.AccountAmount,
		&i.PosID,
		&i.PosAmount,
		&i.CounterpartyID,
		&i.Note,
		&i.Source,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ReversesID,
	)
	return i, err
}

const insertMoneyTransaction = `-- name: InsertMoneyTransaction :one
INSERT INTO transactions (
    type, effective_date,
    account_id, account_amount,
    pos_id, pos_amount,
    counterparty_id, note,
    source, created_by, idempotency_key,
    reverses_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (idempotency_key)
DO UPDATE SET idempotency_key = transactions.idempotency_key  -- no-op so RETURNING fires
RETURNING transactions.id, transactions.type, transactions.effective_date, transactions.account_id, transactions.account_amount, transactions.pos_id, transactions.pos_amount, transactions.counterparty_id, transactions.note, transactions.source, transactions.created_by, transactions.idempotency_key, transactions.created_at, transactions.reverses_id, (xmax = 0) AS was_inserted
`

type InsertMoneyTransactionParams struct {
	Type           TransactionType
	EffectiveDate  pgtype.Date
	AccountID      pgtype.UUID
	AccountAmount  *int64
	PosID          pgtype.UUID
	PosAmount      *int64
	CounterpartyID pgtype.UUID
	Note           *string
	Source         TransactionSource
	CreatedBy      pgtype.UUID
	IdempotencyKey string
	ReversesID     pgtype.UUID
}

type InsertMoneyTransactionRow struct {
	ID             pgtype.UUID
	Type           TransactionType
	EffectiveDate  pgtype.Date
	AccountID      pgtype.UUID
	AccountAmount  *int64
	PosID          pgtype.UUID
	PosAmount      *int64
	CounterpartyID pgtype.UUID
	Note           *string
	Source         TransactionSource
	CreatedBy      pgtype.UUID
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	ReversesID     pgtype.UUID
	WasInserted    bool
}

// Insert a money_in / money_out row. Idempotency: ON CONFLICT on
// idempotency_key returns the existing row; the (xmax = 0) projection
// distinguishes a fresh insert (was_inserted=true) from a conflict
// (was_inserted=false), so the application can skip the notification
// loop on idempotent re-submission per spec §10.8. Duplicate POSTs
// silently return the original record per spec §7.2.
func (q *Queries) InsertMoneyTransaction(ctx context.Context, arg InsertMoneyTransactionParams) (InsertMoneyTransactionRow, error) {
	row := q.db.QueryRow(ctx, insertMoneyTransaction,
		arg.Type,
		arg.EffectiveDate,
		arg.AccountID,
		arg.AccountAmount,
		arg.PosID,
		arg.PosAmount,
		arg.CounterpartyID,
		arg.Note,
		arg.Source,
		arg.CreatedBy,
		arg.IdempotencyKey,
		arg.ReversesID,
	)
	var i InsertMoneyTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EffectiveDate,
		&i.AccountID,
		&i.AccountAmount,
		&i.PosID,
		&i.PosAmount,
		&i.CounterpartyID,
		&i.Note,
		&i.Source,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ReversesID,
		&i.WasInserted,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, type, title, body, related_transaction_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, related_transaction_id, read_at, created_at
`

type InsertNotificationParams struct {
	UserID               pgtype.UUID
	Type                 NotificationType
	Title                string
	Body                 *string
	RelatedTransactionID pgtype.UUID
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.RelatedTransactionID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.RelatedTransactionID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, type, title, body, related_transaction_id, read_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListNotificationsForUser(ctx context.Context, userID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.RelatedTransactionID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObligationsForPos = `-- name: ListObligationsForPos :many
SELECT
    id, transaction_id,
    creditor_pos_id, debtor_pos_id,
    currency, amount_owed, amount_repaid,
    cleared_at, created_at
FROM pos_obligation
WHERE (creditor_pos_id = $1 OR debtor_pos_id = $1)
  AND cleared_at IS NULL
ORDER BY created_at DESC
`

// Open obligations where this pos is creditor (money it's owed) or
// debtor (money it owes). Counts toward Pos.receivables and
// Pos.payables on the detail view per spec §4.2.
func (q *Queries) ListObligationsForPos(ctx context.Context, creditorPosID pgtype.UUID) ([]PosObligation, error) {
	rows, err := q.db.Query(ctx, listObligationsForPos, creditorPosID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PosObligation
	for rows.Next() {
		var i PosObligation
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.CreditorPosID,
			&i.DebtorPosID,
			&i.Currency,
			&i.AmountOwed,
			&i.AmountRepaid,
			&i.ClearedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, type, effective_date, account_id, account_amount, pos_id, pos_amount, counterparty_id, note, source, created_by, idempotency_key, created_at, reverses_id FROM transactions
WHERE account_id = $1
ORDER BY effective_date DESC, created_at DESC
`

func (q *Queries) ListTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EffectiveDate,
			&i.AccountID,
			&i.AccountAmount,
			&i.PosID,
			&i.PosAmount,
			&i.CounterpartyID,
			&i.Note,
			&i.Source,
			&i.CreatedBy,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ReversesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT
    t.id, t.type, t.effective_date,
    t.account_id, t.account_amount,
    t.pos_id, t.pos_amount,
    t.counterparty_id, t.note,
    t.source, t.created_by, t.idempotency_key,
    t.created_at, t.reverses_id,
    a.name  AS account_name,
    p.name  AS pos_name,
    p.currency AS pos_currency,
    cp.name AS counterparty_name
FROM transactions t
LEFT JOIN accounts       a  ON a.id  = t.account_id
LEFT JOIN pos            p  ON p.id  = t.pos_id
LEFT JOIN counterparties cp ON cp.id = t.counterparty_id
WHERE t.effective_date >= $1 AND t.effective_date <= $2
ORDER BY t.effective_date DESC, t.created_at DESC, t.id DESC
LIMIT 200
`

type ListTransactionsByDateRangeParams struct {
	EffectiveDate   pgtype.Date
	EffectiveDate_2 pgtype.Date
}

type ListTransactionsByDateRangeRow struct {
	ID               pgtype.UUID
	Type             TransactionType
	EffectiveDate    pgtype.Date
	AccountID        pgtype.UUID
	AccountAmount    *int64
	PosID            pgtype.UUID
	PosAmount        *int64
	CounterpartyID   pgtype.UUID
	Note             *string
	Source           TransactionSource
	CreatedBy        pgtype.UUID
	IdempotencyKey   string
	CreatedAt        pgtype.Timestamptz
	ReversesID       pgtype.UUID
	AccountName      *string
	PosName          *string
	PosCurrency      *string
	CounterpartyName *string
}

// Joined view for the §6.1 list: account.name, pos.name + currency,
// counterparty.name. LEFT JOINs because Phase 7+ inter_pos rows have
// NULL account_id / pos_id / counterparty_id (line items live in
// inter_pos_lines — to be rendered when that phase ships).
func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]ListTransactionsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRange, arg.EffectiveDate, arg.EffectiveDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByDateRangeRow
	for rows.Next() {
		var i ListTransactionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EffectiveDate,
			&i.AccountID,
			&i.AccountAmount,
			&i.PosID,
			&i.PosAmount,
			&i.CounterpartyID,
			&i.Note,
			&i.Source,
			&i.CreatedBy,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ReversesID,
			&i.AccountName,
			&i.PosName,
			&i.PosCurrency,
			&i.CounterpartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByPos = `-- name: ListTransactionsByPos :many
SELECT
    t.id, t.type, t.effective_date,
    t.account_amount, t.pos_amount, t.note,
    t.created_at, t.reverses_id,
    a.name  AS account_name,
    cp.name AS counterparty_name
FROM transactions t
LEFT JOIN accounts       a  ON a.id  = t.account_id
LEFT JOIN counterparties cp ON cp.id = t.counterparty_id
WHERE t.pos_id = $1
ORDER BY t.effective_date DESC, t.created_at DESC, t.id DESC
LIMIT 200
`

type ListTransactionsByPosRow struct {
	ID               pgtype.UUID
	Type             TransactionType
	EffectiveDate    pgtype.Date
	AccountAmount    *int64
	PosAmount        *int64
	Note             *string
	CreatedAt        pgtype.Timestamptz
	ReversesID       pgtype.UUID
	AccountName      *string
	CounterpartyName *string
}

// Chronological transactions touching this pos. Phase-7+ inter_pos lines
// live in inter_pos_lines and are not yet wired; this query covers the
// money_in / money_out path that Phase 6 ships.
func (q *Queries) ListTransactionsByPos(ctx context.Context, posID pgtype.UUID) ([]ListTransactionsByPosRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByPos, posID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByPosRow
	for rows.Next() {
		var i ListTransactionsByPosRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EffectiveDate,
			&i.AccountAmount,
			&i.PosAmount,
			&i.Note,
			&i.CreatedAt,
			&i.ReversesID,
			&i.AccountName,
			&i.CounterpartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const sumAccountBalances = `-- name: SumAccountBalances :many
SELECT
    a.id,
    COALESCE(SUM(CASE
        WHEN t.type = 'money_in'  THEN t.account_amount
        WHEN t.type = 'money_out' THEN -t.account_amount
        ELSE 0
    END), 0)::bigint AS balance
FROM accounts a
LEFT JOIN transactions t ON t.account_id = a.id
WHERE NOT a.archived
GROUP BY a.id
`

type SumAccountBalancesRow struct {
	ID      pgtype.UUID
	Balance int64
}

// Per-account balance: signed sum of money_in / money_out account_amount
// contributions per account_id, restricted to non-archived accounts. The
// LEFT JOIN keeps zero-balance accounts in the result so the home view's
// list of accounts matches ListAccounts row-for-row.
func (q *Queries) SumAccountBalances(ctx context.Context) ([]SumAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, sumAccountBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumAccountBalancesRow
	for rows.Next() {
		var i SumAccountBalancesRow
		if err := rows.Scan(&i.ID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMoneyOutByPosMonth = `-- name: SumMoneyOutByPosMonth :many
SELECT
    p.id        AS pos_id,
    p.name      AS pos_name,
    p.currency  AS pos_currency,
    date_trunc('month', t.effective_date)::date AS month,
    SUM(t.pos_amount)::bigint AS spent
FROM transactions t
JOIN pos p ON p.id = t.pos_id
WHERE t.type = 'money_out'
  AND t.effective_date >= $1
  AND t.effective_date <= $2
GROUP BY p.id, p.name, p.currency, month
ORDER BY month DESC, spent DESC
`

type SumMoneyOutByPosMonthParams struct {
	EffectiveDate   pgtype.Date
	EffectiveDate_2 pgtype.Date
}

type SumMoneyOutByPosMonthRow struct {
	PosID       pgtype.UUID
	PosName     string
	PosCurrency string
	Month       pgtype.Date
	Spent       int64
}

// Spending heatmap (§6.4): one row per (pos, month) summing pos_amount
// for money_out transactions in the date range. Caller pivots to a
// months × top-N-pos table and computes the top-N ranking from totals.
func (q *Queries) SumMoneyOutByPosMonth(ctx context.Context, arg SumMoneyOutByPosMonthParams) ([]SumMoneyOutByPosMonthRow, error) {
	rows, err := q.db.Query(ctx, sumMoneyOutByPosMonth, arg.EffectiveDate, arg.EffectiveDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumMoneyOutByPosMonthRow
	for rows.Next() {
		var i SumMoneyOutByPosMonthRow
		if err := rows.Scan(
			&i.PosID,
			&i.PosName,
			&i.PosCurrency,
			&i.Month,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPosCashBalances = `-- name: SumPosCashBalances :many
SELECT
    p.id,
    p.currency,
    COALESCE(SUM(CASE
        WHEN t.type = 'money_in'  THEN t.pos_amount
        WHEN t.type = 'money_out' THEN -t.pos_amount
        ELSE 0
    END), 0)::bigint AS balance
FROM pos p
LEFT JOIN transactions t ON t.pos_id = p.id
WHERE NOT p.archived
GROUP BY p.id, p.currency
`

type SumPosCashBalancesRow struct {
	ID       pgtype.UUID
	Currency string
	Balance  int64
}

// Per-pos cash balance: signed sum of money_in / money_out pos_amount per
// (pos_id, currency). inter_pos lines are not yet wired (Phase 7+) so they
// contribute zero. Currency comes from pos.currency since money_in/_out
// always denominate pos_amount in the pos's currency (§4.3 / §5.1).
func (q *Queries) SumPosCashBalances(ctx context.Context) ([]SumPosCashBalancesRow, error) {
	rows, err := q.db.Query(ctx, sumPosCashBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumPosCashBalancesRow
	for rows.Next() {
		var i SumPosCashBalancesRow
		if err := rows.Scan(&i.ID, &i.Currency, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreadCount = `-- name: UnreadCount :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) UnreadCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, unreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
