// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTransaction = `-- name: GetTransaction :one
SELECT id, type, effective_date, account_id, account_amount, pos_id, pos_amount, counterparty_id, note, source, created_by, idempotency_key, created_at, reverses_id FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EffectiveDate,
		&i.AccountID,
		&i.AccountAmount,
		&i.PosID,
		&i.PosAmount,
		&i.CounterpartyID,
		&i.Note,
		&i.Source,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ReversesID,
	)
	return i, err
}

const insertMoneyTransaction = `-- name: InsertMoneyTransaction :one
INSERT INTO transactions (
    type, effective_date,
    account_id, account_amount,
    pos_id, pos_amount,
    counterparty_id, note,
    source, created_by, idempotency_key,
    reverses_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (idempotency_key)
DO UPDATE SET idempotency_key = transactions.idempotency_key  -- no-op so RETURNING fires
RETURNING transactions.id, transactions.type, transactions.effective_date, transactions.account_id, transactions.account_amount, transactions.pos_id, transactions.pos_amount, transactions.counterparty_id, transactions.note, transactions.source, transactions.created_by, transactions.idempotency_key, transactions.created_at, transactions.reverses_id, (xmax = 0) AS was_inserted
`

type InsertMoneyTransactionParams struct {
	Type           TransactionType
	EffectiveDate  pgtype.Date
	AccountID      pgtype.UUID
	AccountAmount  *int64
	PosID          pgtype.UUID
	PosAmount      *int64
	CounterpartyID pgtype.UUID
	Note           *string
	Source         TransactionSource
	CreatedBy      pgtype.UUID
	IdempotencyKey string
	ReversesID     pgtype.UUID
}

type InsertMoneyTransactionRow struct {
	ID             pgtype.UUID
	Type           TransactionType
	EffectiveDate  pgtype.Date
	AccountID      pgtype.UUID
	AccountAmount  *int64
	PosID          pgtype.UUID
	PosAmount      *int64
	CounterpartyID pgtype.UUID
	Note           *string
	Source         TransactionSource
	CreatedBy      pgtype.UUID
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	ReversesID     pgtype.UUID
	WasInserted    bool
}

// Insert a money_in / money_out row. Idempotency: ON CONFLICT on
// idempotency_key returns the existing row; the (xmax = 0) projection
// distinguishes a fresh insert (was_inserted=true) from a conflict
// (was_inserted=false), so the application can skip the notification
// loop on idempotent re-submission per spec §10.8. Duplicate POSTs
// silently return the original record per spec §7.2.
func (q *Queries) InsertMoneyTransaction(ctx context.Context, arg InsertMoneyTransactionParams) (InsertMoneyTransactionRow, error) {
	row := q.db.QueryRow(ctx, insertMoneyTransaction,
		arg.Type,
		arg.EffectiveDate,
		arg.AccountID,
		arg.AccountAmount,
		arg.PosID,
		arg.PosAmount,
		arg.CounterpartyID,
		arg.Note,
		arg.Source,
		arg.CreatedBy,
		arg.IdempotencyKey,
		arg.ReversesID,
	)
	var i InsertMoneyTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.EffectiveDate,
		&i.AccountID,
		&i.AccountAmount,
		&i.PosID,
		&i.PosAmount,
		&i.CounterpartyID,
		&i.Note,
		&i.Source,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.ReversesID,
		&i.WasInserted,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, type, title, body, related_transaction_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, related_transaction_id, read_at, created_at
`

type InsertNotificationParams struct {
	UserID               pgtype.UUID
	Type                 NotificationType
	Title                string
	Body                 *string
	RelatedTransactionID pgtype.UUID
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.RelatedTransactionID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.RelatedTransactionID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, type, title, body, related_transaction_id, read_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListNotificationsForUser(ctx context.Context, userID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.RelatedTransactionID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, type, effective_date, account_id, account_amount, pos_id, pos_amount, counterparty_id, note, source, created_by, idempotency_key, created_at, reverses_id FROM transactions
WHERE account_id = $1
ORDER BY effective_date DESC, created_at DESC
`

func (q *Queries) ListTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.EffectiveDate,
			&i.AccountID,
			&i.AccountAmount,
			&i.PosID,
			&i.PosAmount,
			&i.CounterpartyID,
			&i.Note,
			&i.Source,
			&i.CreatedBy,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.ReversesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const unreadCount = `-- name: UnreadCount :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) UnreadCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, unreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
