// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package dbq

import (
	"context"
)

const getUserByTelegramIdentifier = `-- name: GetUserByTelegramIdentifier :one
SELECT id, display_name, telegram_identifier, created_at FROM users WHERE telegram_identifier = $1
`

func (q *Queries) GetUserByTelegramIdentifier(ctx context.Context, telegramIdentifier string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramIdentifier, telegramIdentifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.TelegramIdentifier,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, display_name, telegram_identifier, created_at FROM users ORDER BY display_name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.TelegramIdentifier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (display_name, telegram_identifier)
VALUES ($1, $2)
ON CONFLICT (telegram_identifier) DO UPDATE
  SET display_name = EXCLUDED.display_name
RETURNING id, display_name, telegram_identifier, created_at
`

type UpsertUserParams struct {
	DisplayName        string
	TelegramIdentifier string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.DisplayName, arg.TelegramIdentifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.TelegramIdentifier,
		&i.CreatedAt,
	)
	return i, err
}
